### ISSUE TITLE
input fields are added multiple when Form has target

### ISSUE THREAD

**Issue by Radon8472** [Radon8472/jquery-form-attribute-polyfill#1]
When the form has an external target and is not refreshing the form-page the inputfields outside of the form are added mutiple times.
Mostly this is problematic when you uncheck a checkbox, because the checked value will still be in the previos added fields.

I already have a bugfix from [fbrueseke] in branch [stackoverflow/a/17742275] that needs to be tested and merged.

## Tasks
- [ ] test if bugfix removes the multiple fields-bug
- [ ] Change code and add `CLASS_NAME_POLYFILL_MARKER` as Data-attribut instead of class
- [ ] test if we can keep the browser support detection-area

[fbrueseke]: https://stackoverflow.com/users/8358563/fbrueseke
[stackoverflow/a/17742275]: /Radon8472/jquery-form-attribute-polyfill/tree/stackoverflow/a/17742275
